QuieroAprender/QuieroAprender/courses/urls.py
from django.urls import path

from QuieroAprender.courses.views import course_detail, course_list
from QuieroAprender.lessons.views import lessons_by_course

urlpatterns = [
    path("all/", course_list, name="all-courses"),
    path("<int:pk>/", course_detail, name="course-detail"),
    path("<int:course_id>/lessons/", lessons_by_course, name="lessons-by-course"),
]

QuieroAprender/QuieroAprender/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("QuieroAprender.common.urls")),
    path("accounts/", include("QuieroAprender.accounts.urls")),
    path("course/", include("QuieroAprender.courses.urls")),
    path("lesson/", include("QuieroAprender.lessons.urls")),
    path("forum/", include("QuieroAprender.forum.urls")),
    path("blog/", include("QuieroAprender.blog.urls")),
    path("events/", include("QuieroAprender.events.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

QuieroAprender/QuieroAprender/courses/models.py
from django.db import models


class Course(models.Model):
    title = models.CharField(max_length=70, unique=True)
    description = models.TextField()
    level = models.CharField(
        max_length=50,
        choices=[
            ("beginner", "Beginner"),
            ("intermediate", "Intermediate"),
            ("advanced", "Advanced"),
        ],
        default="beginner",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_lessons(self):
        return self.lessons.all()

QuieroAprender/QuieroAprender/courses/views.py
from django.shortcuts import render

from QuieroAprender.courses.models import Course


def course_list(request):
    courses = Course.objects.all()
    return render(request, "courses/course-list.html", {"courses": courses})


def course_detail(request, pk):
    course = Course.objects.get(pk=pk)
    context = {"course": course}

    return render(request, "courses/course-detail.html", context)

QuieroAprender/templates/courses/course-detail.html
{% extends 'base.html' %}

{% block title %}
	Course Details
{% endblock %}

{% block content %}
	<div class="course-container">
        <h1 class="course-title">{{ course.title }}</h1>
        <p class="course-description">{{ course.description }}</p>
        <p class="course-level">
            <strong>Level:</strong> {{ course.get_level_display }}
        </p>
        {% if user.is_authenticated %}
        	<a class="course-link" href="{% url 'lessons-by-course' course.id %}">View Lessons</a>
        {% endif %} 
    </div>
{% endblock %}

QuieroAprender/templates/courses/course-list.html
{% extends 'base.html' %}

{% block title %}
	Courses
{% endblock %}

{% block content %}
    
	<div class="course-container">
    <h1 class="course-title">AVAILABLE COURSES</h1>
        <br>
    <ul class="course-list">
        {% for course in courses %}
            <li class="course-item">
                <div class="course-content">
                    <h3 class="course-title">{{ course.title }}</h3>
                    <p class="course-description">{{ course.description }}</p>
                    <p class="course-level">
                        <strong>Level:</strong> {{ course.get_level_display }}
                    </p>
                </div>
                {% if user.is_authenticated %}
                    <a class="course-link" href="{% url 'lessons-by-course' course.id %}">View Lessons</a>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}